# Generated by Django 6.0.2 on 2026-03-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='check_type',
            field=models.CharField(choices=[('entry', 'Kirish'), ('exit', 'Chiqish'), ('both', 'Ikkalasi')], default='both', max_length=10),
        ),
    ]
