import React, { createContext, useContext, useState } from 'react';

export type Lang = 'uz' | 'ru' | 'en';

const translations: Record<Lang, Record<string, string>> = {
  uz: {
    // Nav
    dashboard: "Dashboard", monitoring: "Jonli kuzatuv", attendance: "Davomat",
    employees: "Xodimlar", leaves: "Ta'tillar", payroll: "Maosh",
    devices: "Qurilmalar", team: "Jamoa", reports: "Hisobotlar",
    settings: "Sozlamalar", notifications: "Bildirishnomalar", logout: "Chiqish",
    // General
    search: "Qidirish...", save: "Saqlash", saving: "Saqlanmoqda...", saved: "Saqlandi!",
    cancel: "Bekor qilish", delete: "O'chirish", edit: "Tahrirlash", export: "Eksport",
    saveChanges: "O'zgarishlarni saqlash",
    loading: "Yuklanmoqda...", noData: "Ma'lumot yo'q", noNotifications: "Bildirishnoma yo'q",
    viewAll: "Barchasini ko'rish", refresh: "Yangilash", add: "Qo'shish",
    profile: "Profil", language: "Til", theme: "Mavzu", light: "Yorug'", dark: "Tungi",
    company: "Kompaniya", schedule: "Ish jadvali", security: "Xavfsizlik",
    email: "Email", status: "Holat", thisMonth: "Shu oy",
    // Dashboard
    systemOverview: "Tizim ko'rinishi",
    presentToday: "Bugun kelganlar", lateArrivals: "Kechikkanlar",
    absent: "Kelmaganlar", totalHours: "Jami soatlar",
    weeklyAttendance: "Haftalik davomat", last7Days: "So'nggi 7 kun",
    present: "Keldi", late: "Kech", liveCheckins: "Jonli kirishlar",
    realtimeFeed: "Real-vaqt yangilanish", noCheckins: "Bugun hali kirish qayd etilmagan",
    viewAllRecords: "Barcha yozuvlarni ko'rish →",
    byDepartment: "Bo'lim bo'yicha", checkinMethods: "Kirish usullari",
    quickActions: "Tezkor amallar", viewAttendance: "Davomatni ko'rish",
    runReport: "Hisobot yaratish", viewMonitoring: "Jonli kuzatuvni ko'rish",
    manageCameras: "Kameralarni boshqarish", employeeProfiles: "Xodim profillari",
    vsYesterday: "kechagiga nisbatan", thisWeek: "bu hafta",
    // Live Monitoring
    liveMonitoring: "Jonli kuzatuv",
    realtimeTracking: "Real-vaqt xodimlar kuzatuvi",
    updatedAt: "Yangilangan", totalEmployees: "Jami xodimlar",
    insideOffice: "Ofisda", outsideAway: "Tashqarida / Ketdi",
    absentToday: "Bugun kelmadi", allFilter: "Barchasi",
    insideFilter: "Ichkarida", outsideFilter: "Tashqarida",
    searchEmployees: "Xodimlarni qidirish...",
    noOneInOffice: "Hozir hech kim ofisda emas",
    noMatchSearch: "Qidiruv bo'yicha hech kim topilmadi",
    workedFrom: "Kirish", checkIn: "Kirish", checkOut: "Chiqish", off: "Dam olish",
    // Attendance
    attendanceLog: "Davomat jurnali",
    recordsFound: "ta yozuv", addRecord: "Yozuv qo'shish",
    myStatus: "Mening holatim", checkInBtn: "Kirish", checkOutBtn: "Chiqish",
    completedToday: "Bugun bajarildi", onSiteNow: "Hozir ishda",
    cameToday: "bugun keldi", arrivedLate: "Kech keldi", didntCome: "Kelmadi",
    employee: "Xodim", date: "Sana", duration: "Davomiylik", method: "Usul", actions: "Amallar",
    checkInTime: "Kirish vaqti", checkOutTime: "Chiqish vaqti",
    allStatuses: "Barcha statuslar", onTime: "O'z vaqtida",
    earlyLeave: "Erta ketdi", allMethods: "Barcha usullar",
    allEmployees: "Barcha xodimlar", allDepts: "Barcha bo'limlar",
    from: "Dan", to: "Gacha", clearFilters: "Tozalash",
    noRecords: "Yozuv topilmadi", tryFilters: "Filtrlarni tozalab ko'ring",
    previous: "Oldingi", next: "Keyingi",
    addAttendance: "Davomat yozuvi qo'shish", selectEmployee: "Xodimni tanlang",
    notCheckedIn: "Hali kirish qayd etilmagan", currentlyInOffice: "Kirish qayd etildi",
    deleteConfirm: "Bu yozuvni o'chirishga rozimisiz?",
    recordAdded: "Yozuv muvaffaqiyatli qo'shildi!", recordDeleted: "Yozuv o'chirildi",
    checkInSuccess: "Kirish muvaffaqiyatli qayd etildi!",
    checkOutSuccess: "Chiqish muvaffaqiyatli qayd etildi!",
    // Employees
    employeeName: "Xodim ismi", lastName: "Familiya", firstName: "Ism",
    phone: "Telefon", password: "Parol", role: "Rol", department: "Bo'lim",
    searchPlaceholder: "Ism yoki telefon bo'yicha qidirish...",
    filters: "Filtrlar", todayStatus: "Bugungi holat",
    photo: "Rasm", photoOptional: "Rasm (ixtiyoriy)",
    errorOccurred: "Xatolik yuz berdi", employeeAdded: "Xodim muvaffaqiyatli qo'shildi",
    addNewEmployee: "Yangi xodim qo'shish", fillAllFields: "Majburiy maydonlarni to'ldiring",
    selectDepartment: "Bo'limni tanlang", noDepartment: "Bo'limsiz",
    addDepartment: "Bo'lim qo'shish", departmentName: "Bo'lim nomi",
    createDepartment: "Yaratish", departmentCreated: "Bo'lim yaratildi!",
    allDepartments: "Barcha bo'limlar", filterByDept: "Bo'lim bo'yicha...",
    // Employee Profile
    employeeProfile: "Xodim profili", profileSubtitle: "Xodim ma'lumotlarini ko'rish va boshqarish",
    deactivate: "Faolsizlantirish", editProfile: "Profilni tahrirlash",
    faceIdEnrollment: "Face ID ro'yxatga olish", notSet: "O'RNATILMAGAN",
    faceEnrolled: "Face biometrikasi ro'yxatga olindi",
    noFaceData: "Face ID ma'lumotlari mavjud emas. Xodim uchun Face ID sozlash uchun quyidagini bosing.",
    reEnroll: "Qayta ro'yxatga olish", enrollFace: "Face ro'yxatga olish",
    contactDetails: "Aloqa ma'lumotlari", joined: "Qo'shilgan",
    lastCheckIn: "Oxirgi kirish", monthlyStats: "Oylik statistika",
    daysOff: "Dam olish kunlari", attendanceHeatmap: "Davomat xaritasi",
    recentRecords: "Oxirgi yozuvlar", attendanceRate: "davomat ko'rsatkichi",
    confirmDeactivate: "Xodimni faolsizlantirishni (deactivate) tasdiqlaysizmi?",
    confirmDeleteFace: "Face ID ma'lumotlarini o'chirishni tasdiqlaysizmi?",
    profileUpdated: "Profil yangilandi", faceSaved: "Face ID muvaffaqiyatli saqlandi!",
    // Leaves
    leavesSubtitle: "Dam olish va ta'til so'rovlarini boshqarish", newRequest: "Yangi so'rov",
    remaining: "Qolgan", left: "qoldi", used: "Ishlatilgan", total: "Jami",
    leaveType: "Ta'til turi", startDate: "Boshlanish sanasi", endDate: "Tugash sanasi",
    days: "Kunlar", reason: "Sabab", newLeaveRequest: "Yangi ta'til so'rovi",
    selectType: "Turini tanlang", whyNeedLeave: "Nima uchun ushbu ta'til kerak?",
    submitRequest: "So'rovni yuborish", requestSubmitted: "So'rov muvaffaqiyatli yuborildi!",
    errorSubmitting: "So'rovni yuborishda xatolik yuz berdi",
    // Payroll
    payrollManagement: "Maosh boshqaruvi", payrollSubtitle: "Xodimlar ish haqi va hisob-kitoblarini boshqarish",
    payrollRecords: "Maosh yozuvlari", salaryConfig: "Ish haqi sozlamalari",
    workDays: "Ish kunlari", workHours: "Ish soatlari", overtimeHours: "Q.ish soatlari",
    baseSalary: "Asosiy maosh", overtimePay: "Q.ish to'lovi", netSalary: "Jami maosh",
    configureSalary: "Ish haqi sozlash", salaryType: "Ish haqi turi",
    hourly: "Soatlik", daily: "Kunlik", monthly: "Oylik",
    amount: "Miqdor", overtimeRate: "Koeffitsient", calculateSalary: "Maosh hisoblash",
    calculationMonth: "Hisoblash oyi", calculating: "Hisoblanmoqda...",
    enterAmount: "To'g'ri miqdor kiriting", configSaved: "Sozlama saqlandi",
    errorCalculating: "Hisoblashda xatolik", deleteConfigConfirm: "Sozlamani o'chirishni tasdiqlaysizmi?",
    calculateSubtitle: "Tanlangan oy uchun barcha xodimlarning maoshini davomat ma'lumotlari asosida hisoblaydi.",
    workDaysDesc: "Davomat yozuvlari asosida", overtimeDesc: "Ish haqi sozlamasidagi koeff. bilan",
    // Team
    teamManagement: "Jamoa boshqaruvi", teamSubtitle: "Xodimlarni qo'shish, rollarini belgilash va boshqarish",
    addEmployee: "Xodim qo'shish", contact: "Aloqa", dateJoined: "Qo'shilgan sana",
    notAssigned: "Belgilanmagan", assignRole: "Rol belgilash", changeRole: "Rolni o'zgartiring",
    enterUserDetails: "Xodim ma'lumotlarini kiriting", editRole: "Rolni tahrirlash",
    selectNewRole: "Yangi rol tanlang", roleSaved: "Rol muvaffaqiyatli saqlandi!",
    teamConfirmDeactivate: "ni tizimdan o'chirmoqchimisiz? Bu amalni qaytarib bo'lmaydi.",
    teamSearchPlaceholder: "Ism, email yoki telefon bo'yicha qidiring...",
    totalCount: "Jami",
    roleOwner: "Barcha huquqlarga ega kompaniya rahbari",
    roleAdmin: "Keng boshqaruv huquqlari",
    roleManager: "Davomat va hisobotlarni ko'rish",
    roleHr: "Xodimlar boshqaruvi va ta'tillar",
    roleAccountant: "Maosh hisoblash va moliyaviy hisobotlar",
    roleEmployee: "Faqat o'z ma'lumotlarini ko'rish",
    roleGuard: "Davomat kuzatuvi",
    // Reports
    reportsPage: "Hisobotlar",
    reportsSubtitle: "Davomat hisobotlarini shakllantirish va yuklab olish",
    reportConfig: "Hisobot sozlamalari",
    reportType: "Hisobot turi",
    dateFrom: "Dan",
    dateTo: "Gacha",
    generate: "Shakllantirish",
    generating: "Shakllantirilmoqda...",
    dataAnalytics: "Ma'lumotlar tahlili",
    noAnalytics: "Grafiklar faqat umumiy boshqaruv panelida mavjud.",
    totalEmployeesReport: "Jami xodimlar",
    avgAttendanceReport: "O'rtacha davomat",
    totalHoursReport: "Jami soatlar",
    lateArrivalsReport: "Kechikishlar",
    absencesReport: "Kelmaganlar",
    reportPreview: "Hisobotni ko'rish",
    presentDays: "Kelgan kunlar",
    lateDays: "Kechikkan kunlar",
    absentDays: "Kelmaganlar kunlar",
    overtime: "Qo'shimcha vaqt",
    rate: "Ko'rsatkich %",
    reportGenerated: "Hisobot muvaffaqiyatli shakllantirildi",
    reportExported: "Hisobot yuklab olindi",
    exportFailed: "Yuklab olishda xatolik",
    attendanceSummary: "Davomat xulosasi",
    lateArrivalsReportFile: "Kechikishlar hisoboti",
    absenceReport: "Kelmaganlar hisoboti",
    hoursWorkedReport: "Ish soatlari hisoboti",
    departmentSummary: "Bo'limlar xulosasi",
    // Devices
    devicesManagement: "Qurilmalar boshqaruvi",
    devicesSubtitle: "Kameralar va Yuz ID qurilmalarini ulash va boshqarish",
    addCamera: "Kamera qo'shish",
    addFaceId: "Yuz ID qo'shish",
    cameras: "Kameralar",
    faceIdDevices: "Yuz ID qurilmalari",
    noDevices: "Hali qurilma qo'shilmagan",
    addFirstDevice: "Yuqoridagi tugmani bosib yangi qurilma qo'shing",
    testConnection: "Ulanishni tekshirish",
    testingConnection: "Tekshirilmoqda...",
    lastCheck: "Oxirgi tekshiruv",
    deviceName: "Qurilma nomi",
    location: "Joylashuv",
    ipAddress: "IP manzil",
    port: "Port",
    macAddress: "MAC manzil",
    rtspUrl: "RTSP URL",
    username: "Foydalanuvchi nomi",
    checkType: "Tekshiruv turi",
    both: "Kirish & Chiqish",
    entryOnly: "Faqat kirish",
    exitOnly: "Faqat chiqish",
    faceThreshold: "Yuz aniqlash chegarasi",
    soft: "Yumshoq",
    strict: "Qattiq",
    networkSettings: "Tarmoq sozlamalari",
    deviceLogin: "Qurilma login ma'lumotlari",
    deviceSettings: "Qurilma sozlamalari",
    apiKey: "API Kalit",
    copy: "Nusxa olish",
    confirmDeleteDevice: "Qurilmani o'chirishni tasdiqlaysizmi?",
    deviceAdded: "Qurilma muvaffaqiyatli qo'shildi",
    deviceDeleted: "Qurilma o'chirildi",
    connectionSuccess: "Ulanish muvaffaqiyatli!",
    connectionFailed: "Ulanishda xatolik",
    serverError: "Server xatoligi",
    entryHistory: "Kirish tarixi",
    successful: "Muvaffaqiyatli",
    rejected: "Rad etilgan",
    successRate: "Darajasi",
    noHistory: "Tarix yo'q",
    unknown: "Noma'lum",
    enrolledFaces: "Ro'yxatdagi yuzlar",
    employeesEnrolled: "ta xodim ro'yxatda",
    noOneEnrolled: "Ro'yxatda hech kim yo'q",
    enrolled: "Ro'yxatda",
    deleteFace: "Yuzni o'chirish",
    viewHistory: "Tarixni ko'rish",
    deviceNameRequired: "Qurilma nomi kiritilishi shart.",
    ipRequired: "IP manzil kiritilishi shart.",
    deviceUpdated: "Qurilma yangilandi",
    faceDataDeleted: "Yuz ma'lumoti o'chirildi",
    apiKeyCopied: "API kaliti nusxalandi",
    editDevice: "Qurilmani tahrirlash",
    mainInfo: "Asosiy ma'lumotlar",
    newPasswordOptional: "Yangi parol (ixtiyoriy)",
    unchanged: "O'zgartirilmaydi",
    noDevice: "Qurilma yo'q",
    unknownStatus: "Noma'lum holat",
    // Settings
    settingsSubtitle: "Kompaniya va tizim sozlamalarini boshqarish",
    profileData: "Shaxsiy ma'lumotlar",
    profileDataSubtitle: "Profil ma'lumotlaringizni tahrirlang",
    appearanceSubtitle: "Til va mavzu tanlamlari",
    interfaceLanguage: "Interfeys tili",
    companyData: "Kompaniya ma'lumotlari",
    companySubtitle: "Kompaniyangiz asosiy ma'lumotlarini tahrirlang",
    workSchedule: "Ish jadvali",
    workScheduleSubtitle: "Ish vaqti, tanaffus va qo'shimcha ish soatlari sozlamalari",
    notificationsSubtitle: "Qaysi hodisalar uchun bildirishnoma olish kerakligini tanlang",
    notifLate: "Xodim kechikganda xabar berish",
    notifAbsent: "Xodim kelmaganda xabar berish",
    notifOvertime: "Qo'shimcha ish soatlari haqida xabar berish",
    notifLeave: "Ta'til so'rovlari haqida xabar berish",
    securitySubtitle: "Parolni o'zgartirish",
    currentPassword: "Joriy parol",
    newPassword: "Yangi parol",
    confirmNewPassword: "Yangi parolni tasdiqlash",
    passwordHint: "Kamida 8 ta belgi",
    passwordRequired: "Barcha maydonlarni to'ldiring.",
    passwordLengthError: "Yangi parol kamida 8 ta belgi bo'lishi kerak.",
    passwordMatchError: "Parollar mos tushmadi.",
    passwordChangeError: "Parolni o'zgartirishda xatolik.",
    saveError: "Saqlashda xatolik.",
    timezone: "Vaqt mintaqasi",
    workStart: "Ish boshlanish vaqti",
    workEnd: "Ish tugash vaqti",
    lunchTime: "Tushlik tanaffusi (daqiqa)",
    lateGrace: "Kechikish chegarasi (daqiqa)",
    lateGraceHint: "Shu daqiqagacha kechikish hisoblanmaydi",
    overtimeStart: "Qo'shimcha ish soati boshlanishi (daqiqa)",
    overtimeStartHint: "Ish tugashidan necha daqiqa keyin qo'shimcha ish hisoblanadi",
  },
  ru: {
    dashboard: "Дашборд", monitoring: "Мониторинг", attendance: "Посещаемость",
    employees: "Сотрудники", leaves: "Отпуска", payroll: "Зарплата",
    devices: "Устройства", team: "Команда", reports: "Отчёты",
    settings: "Настройки", notifications: "Уведомления", logout: "Выход",
    search: "Поиск...", save: "Сохранить", saving: "Сохранение...", saved: "Сохранено!",
    cancel: "Отмена", delete: "Удалить", edit: "Редактировать", export: "Экспорт",
    saveChanges: "Сохранить изменения",
    loading: "Загрузка...", noData: "Нет данных", noNotifications: "Нет уведомлений",
    viewAll: "Смотреть всё", refresh: "Обновить", add: "Добавить",
    profile: "Профиль", language: "Язык", theme: "Тема", light: "Светлая", dark: "Тёмная",
    company: "Компания", schedule: "Расписание", security: "Безопасность",
    email: "Email", status: "Статус", thisMonth: "В этом месяце",
    systemOverview: "Обзор системы",
    presentToday: "Присутствуют", lateArrivals: "Опоздания",
    absent: "Отсутствуют", totalHours: "Всего часов",
    weeklyAttendance: "Недельная посещаемость", last7Days: "Последние 7 дней",
    present: "Присутствует", late: "Опоздал", liveCheckins: "Отметки в реальном времени",
    realtimeFeed: "Обновления в реальном времени", noCheckins: "Сегодня нет отметок",
    viewAllRecords: "Смотреть все записи →",
    byDepartment: "По отделам", checkinMethods: "Методы отметки",
    quickActions: "Быстрые действия", viewAttendance: "Посещаемость",
    runReport: "Создать отчёт", viewMonitoring: "Мониторинг",
    manageCameras: "Управление камерами", employeeProfiles: "Профили сотрудников",
    vsYesterday: "вчера", thisWeek: "эта неделя",
    liveMonitoring: "Мониторинг в реальном времени",
    realtimeTracking: "Отслеживание сотрудников в реальном времени",
    updatedAt: "Обновлено", totalEmployees: "Всего сотрудников",
    insideOffice: "В офисе", outsideAway: "За пределами",
    absentToday: "Отсутствуют", allFilter: "Все",
    insideFilter: "Внутри", outsideFilter: "Снаружи",
    searchEmployees: "Поиск сотрудников...",
    noOneInOffice: "Никого нет в офисе",
    noMatchSearch: "Нет совпадений",
    workedFrom: "Вход", checkIn: "Вход", checkOut: "Выход", off: "Выходной",
    attendanceLog: "Журнал посещаемости",
    recordsFound: "записей", addRecord: "Добавить запись",
    myStatus: "Мой статус", checkInBtn: "Войти", checkOutBtn: "Выйти",
    completedToday: "Выполнено сегодня", onSiteNow: "Сейчас на месте",
    cameToday: "пришли сегодня", arrivedLate: "Опоздал", didntCome: "Не пришёл",
    employee: "Сотрудник", date: "Дата", duration: "Продолжительность", method: "Метод", actions: "Действия",
    checkInTime: "Время входа", checkOutTime: "Время выхода",
    allStatuses: "Все статусы", onTime: "Вовремя",
    earlyLeave: "Ушёл рано", allMethods: "Все методы",
    allEmployees: "Все сотрудники", allDepts: "Все отделы",
    from: "С", to: "До", clearFilters: "Очистить",
    noRecords: "Записей нет", tryFilters: "Попробуйте очистить фильтры",
    previous: "Назад", next: "Следующий",
    addAttendance: "Добавить запись посещаемости", selectEmployee: "Выберите сотрудника",
    notCheckedIn: "Вход не зарегистрирован", currentlyInOffice: "Вход зарегистрирован",
    deleteConfirm: "Удалить эту запись?",
    recordAdded: "Запись успешно добавлена!", recordDeleted: "Запись удалена",
    checkInSuccess: "Вход успешно зарегистрирован!",
    checkOutSuccess: "Выход успешно зарегистрирован!",
    // Employees
    employeeName: "Имя сотрудника", lastName: "Фамилия", firstName: "Имя",
    phone: "Телефон", password: "Пароль", role: "Роль", department: "Отдел",
    searchPlaceholder: "Поиск по имени или телефону...",
    filters: "Фильтры", todayStatus: "Статус сегодня",
    photo: "Фото", photoOptional: "Фото (необязательно)",
    errorOccurred: "Произошла ошибка", employeeAdded: "Сотрудник успешно добавлен",
    addNewEmployee: "Добавить нового сотрудника", fillAllFields: "Заполните обязательные поля",
    selectDepartment: "Выберите отдел", noDepartment: "Без отдела",
    addDepartment: "Добавить отдел", departmentName: "Название отдела",
    createDepartment: "Создать", departmentCreated: "Отдел создан!",
    allDepartments: "Все отделы", filterByDept: "По отделу...",
    // Employee Profile
    employeeProfile: "Профиль сотрудника", profileSubtitle: "Просмотр и управление данными сотрудника",
    deactivate: "Деактивировать", editProfile: "Редактировать профиль",
    faceIdEnrollment: "Регистрация Face ID", notSet: "НЕ УСТАНОВЛЕНО",
    faceEnrolled: "Биометрия лица зарегистрирована",
    noFaceData: "Данные лица не зарегистрированы. Нажмите ниже, чтобы настроить Face ID для этого сотрудника.",
    reEnroll: "Перерегистрировать", enrollFace: "Зарегистрировать лицо",
    contactDetails: "Контактная информация", joined: "Присоединился",
    lastCheckIn: "Последний вход", monthlyStats: "Статистика за месяц",
    daysOff: "Выходные дни", attendanceHeatmap: "Тепловая карта посещаемости",
    recentRecords: "Последние записи", attendanceRate: "уровень посещаемости",
    confirmDeactivate: "Вы уверены, что хотите деактивировать сотрудника?",
    confirmDeleteFace: "Вы уверены, что хотите удалить данные Face ID?",
    profileUpdated: "Профиль обновлен", faceSaved: "Face ID успешно сохранен!",
    // Leaves
    leavesSubtitle: "Управление запросами на отпуск и отдых", newRequest: "Новый запрос",
    remaining: "Осталось", left: "осталось", used: "Использовано", total: "Всего",
    leaveType: "Тип отпуска", startDate: "Дата начала", endDate: "Дата окончания",
    days: "Дни", reason: "Причина", newLeaveRequest: "Новый запрос на отпуск",
    selectType: "Выберите тип", whyNeedLeave: "Почему вам нужен этот отпуск?",
    submitRequest: "Отправить запрос", requestSubmitted: "Запрос успешно отправлен!",
    errorSubmitting: "Ошибка при отправке запроса",
    // Payroll
    payrollManagement: "Управление зарплатой", payrollSubtitle: "Управление оплатой труда и расчетами сотрудников",
    payrollRecords: "Записи о зарплате", salaryConfig: "Настройки зарплаты",
    workDays: "Раб. дни", workHours: "Раб. часы", overtimeHours: "Сверхурочные",
    baseSalary: "Осн. зарплата", overtimePay: "Доплата за переработку", netSalary: "Итого к выплате",
    configureSalary: "Настроить зарплату", salaryType: "Тип оплаты",
    hourly: "Почасовая", daily: "Ежедневная", monthly: "Ежемесячная",
    amount: "Сумма", overtimeRate: "Коэффициент", calculateSalary: "Рассчитать зарплату",
    calculationMonth: "Месяц расчета", calculating: "Идет расчет...",
    enterAmount: "Введите корректную сумму", configSaved: "Настройка сохранена",
    errorCalculating: "Ошибка при расчете", deleteConfigConfirm: "Подтвердите удаление настройки?",
    calculateSubtitle: "Рассчитывает зарплату всех сотрудников за выбранный месяц на основе данных о посещаемости.",
    workDaysDesc: "На основе записей посещаемости", overtimeDesc: "С коэфф. из настроек зарплаты",
    // Team
    teamManagement: "Управление командой", teamSubtitle: "Добавление сотрудников, назначение ролей и управление",
    addEmployee: "Добавить сотрудника", contact: "Контакт", dateJoined: "Дата присоединения",
    notAssigned: "Не назначено", assignRole: "Назначить роль", changeRole: "Изменить роль",
    enterUserDetails: "Введите данные сотрудника", editRole: "Редактировать роль",
    selectNewRole: "Выберите новую роль", roleSaved: "Роль успешно сохранена!",
    teamConfirmDeactivate: "вы уверены, что хотите деактивировать пользователя? Это действие необратимо.",
    teamSearchPlaceholder: "Поиск по имени, почте или телефону...",
    totalCount: "Всего",
    roleOwner: "Владелец компании со всеми правами",
    roleAdmin: "Широкие права управления",
    roleManager: "Просмотр посещаемости и отчетов",
    roleHr: "Управление персоналом и отпусками",
    roleAccountant: "Расчет зарплаты и финансовые отчеты",
    roleEmployee: "Просмотр только своих данных",
    roleGuard: "Мониториринг посещаемости",
    // Reports
    reportsPage: "Отчеты",
    reportsSubtitle: "Формирование и экспорт отчетов о посещаемости",
    reportConfig: "Конфигурация отчета",
    reportType: "Тип отчета",
    dateFrom: "С",
    dateTo: "По",
    generate: "Сформировать",
    generating: "Формирование...",
    dataAnalytics: "Аналитика данных",
    noAnalytics: "Графики доступны только в панели управления.",
    totalEmployeesReport: "Всего сотрудников",
    avgAttendanceReport: "Сред. посещаемость",
    totalHoursReport: "Всего часов",
    lateArrivalsReport: "Опоздания",
    absencesReport: "Пропуски",
    reportPreview: "Предпросмотр отчета",
    presentDays: "Явочные дни",
    lateDays: "Дни опозданий",
    absentDays: "Дни пропусков",
    overtime: "Сверхурочные",
    rate: "Показатель %",
    reportGenerated: "Отчет успешно сформирован",
    reportExported: "Отчет успешно экспортирован",
    exportFailed: "Ошибка экспорта",
    attendanceSummary: "Сводка посещаемости",
    lateArrivalsReportFile: "Отчет об опозданиях",
    absenceReport: "Отчет о пропусках",
    hoursWorkedReport: "Отчет об отработанных часах",
    departmentSummary: "Сводка по отделам",
    // Devices
    devicesManagement: "Управление устройствами",
    devicesSubtitle: "Подключение и управление камерами и устройствами Face ID",
    addCamera: "Добавить камеру",
    addFaceId: "Добавить Face ID",
    cameras: "Камеры",
    faceIdDevices: "Устройства Face ID",
    noDevices: "Устройства еще не добавлены",
    addFirstDevice: "Нажмите кнопку выше, чтобы добавить новое устройство",
    testConnection: "Проверить соединение",
    testingConnection: "Проверка...",
    lastCheck: "Последняя проверка",
    deviceName: "Название устройства",
    location: "Расположение",
    ipAddress: "IP адрес",
    port: "Порт",
    macAddress: "MAC адрес",
    rtspUrl: "RTSP URL",
    username: "Имя пользователя",
    checkType: "Тип проверки",
    both: "Вход и Выход",
    entryOnly: "Только вход",
    exitOnly: "Только выход",
    faceThreshold: "Порог распознавания лица",
    soft: "Мягкий",
    strict: "Строгий",
    networkSettings: "Сетевые настройки",
    deviceLogin: "Данные для входа в устройство",
    deviceSettings: "Настройки устройства",
    apiKey: "API Ключ",
    copy: "Копировать",
    confirmDeleteDevice: "Вы уверены, что хотите удалить устройство?",
    deviceAdded: "Устройство успешно добавлено",
    deviceDeleted: "Устройство удалено",
    connectionSuccess: "Соединение успешно!",
    connectionFailed: "Ошибка соединения",
    serverError: "Ошибка сервера",
    entryHistory: "История входа",
    successful: "Успешно",
    rejected: "Отклонено",
    successRate: "Уровень",
    noHistory: "Нет истории",
    unknown: "Неизвестно",
    enrolledFaces: "Зарегистрированные лица",
    employeesEnrolled: "сотрудников в списке",
    noOneEnrolled: "Никого нет в списке",
    enrolled: "В списке",
    deleteFace: "Удалить лицо",
    viewHistory: "Посмотреть историю",
    deviceNameRequired: "Название устройства обязательно.",
    ipRequired: "IP адрес обязателен.",
    deviceUpdated: "Устройство обновлено",
    faceDataDeleted: "Данные лица удалены",
    apiKeyCopied: "API ключ скопирован",
    editDevice: "Редактировать устройство",
    mainInfo: "Основная информация",
    newPasswordOptional: "Новый пароль (необязательно)",
    unchanged: "Не изменяется",
    noDevice: "Нет устройств",
    unknownStatus: "Неизвестный статус",
    // Settings
    settingsSubtitle: "Управление настройками компании и системы",
    profileData: "Личные данные",
    profileDataSubtitle: "Редактируйте данные вашего профиля",
    appearanceSubtitle: "Настройки языка и темы",
    interfaceLanguage: "Язык интерфейса",
    companyData: "Данные компании",
    companySubtitle: "Редактируйте основные данные вашей компании",
    workSchedule: "Рабочий график",
    workScheduleSubtitle: "Настройки рабочего времени, перерывов и сверхурочных",
    notificationsSubtitle: "Выберите, для каких событий вы хотите получать уведомления",
    notifLate: "Уведомлять при опоздании сотрудника",
    notifAbsent: "Уведомлять при отсутствии сотрудника",
    notifOvertime: "Уведомлять о сверхурочных часах",
    notifLeave: "Уведомлять о запросах на отпуск",
    securitySubtitle: "Изменение пароля",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmNewPassword: "Подтверждение нового пароля",
    passwordHint: "Минимум 8 символов",
    passwordRequired: "Заполните все поля.",
    passwordLengthError: "Новый пароль должен содержать минимум 8 символов.",
    passwordMatchError: "Пароли не совпадают.",
    passwordChangeError: "Ошибка при изменении пароля.",
    saveError: "Ошибка при сохранении.",
    timezone: "Часовой пояс",
    workStart: "Время начала работы",
    workEnd: "Время завершения работы",
    lunchTime: "Обеденный перерыв (мин)",
    lateGrace: "Порог опоздания (мин)",
    lateGraceHint: "Опоздание до этого времени не засчитывается",
    overtimeStart: "Начало сверхурочных (мин)",
    overtimeStartHint: "Через сколько минут после работы начинается сверхурочное время",
  },
  en: {
    dashboard: "Dashboard", monitoring: "Live Monitoring", attendance: "Attendance",
    employees: "Employees", leaves: "Leaves", payroll: "Payroll",
    devices: "Devices", team: "Team", reports: "Reports",
    settings: "Settings", notifications: "Notifications", logout: "Logout",
    search: "Search...", save: "Save", saving: "Saving...", saved: "Saved!",
    cancel: "Cancel", delete: "Delete", edit: "Edit", export: "Export",
    saveChanges: "Save Changes",
    loading: "Loading...", noData: "No data available", noNotifications: "No notifications",
    viewAll: "View all", refresh: "Refresh", add: "Add",
    profile: "Profile", language: "Language", theme: "Theme", light: "Light", dark: "Dark",
    company: "Company", schedule: "Schedule", security: "Security",
    email: "Email", status: "Status", thisMonth: "This month",
    systemOverview: "System Overview",
    presentToday: "Present Today", lateArrivals: "Late Arrivals",
    absent: "Absent", totalHours: "Total Hours",
    weeklyAttendance: "Weekly Attendance", last7Days: "Last 7 Days",
    present: "Present", late: "Late", liveCheckins: "Live Check-ins",
    realtimeFeed: "Real-time feed", noCheckins: "No check-ins yet today",
    viewAllRecords: "View All Records →",
    byDepartment: "By Department", checkinMethods: "Check-in Methods",
    quickActions: "Quick Actions", viewAttendance: "View Attendance",
    runReport: "Run Attendance Report", viewMonitoring: "View Live Monitoring",
    manageCameras: "Manage Cameras", employeeProfiles: "Employee Profiles",
    vsYesterday: "vs yesterday", thisWeek: "this week",
    liveMonitoring: "Live Monitoring",
    realtimeTracking: "Real-time employee tracking",
    updatedAt: "Updated", totalEmployees: "Total Employees",
    insideOffice: "Inside Office", outsideAway: "Outside / Away",
    absentToday: "Absent Today", allFilter: "All",
    insideFilter: "Inside", outsideFilter: "Outside",
    searchEmployees: "Search employees...",
    noOneInOffice: "No one is in the office right now",
    noMatchSearch: "No employees match your search",
    workedFrom: "Check-in", checkIn: "Check-in", checkOut: "Check-out", off: "Day Off",
    attendanceLog: "Attendance Log",
    recordsFound: "records found", addRecord: "Add Record",
    myStatus: "My Status", checkInBtn: "Check In", checkOutBtn: "Check Out",
    completedToday: "Completed Today", onSiteNow: "On Site Now",
    cameToday: "came today", arrivedLate: "Late", didntCome: "Absent",
    employee: "Employee", date: "Date", duration: "Duration", method: "Method", actions: "Actions",
    checkInTime: "Check-in Time", checkOutTime: "Check-out Time",
    allStatuses: "All Statuses", onTime: "On Time",
    earlyLeave: "Early Leave", allMethods: "All Methods",
    allEmployees: "All Employees", allDepts: "All Departments",
    from: "From", to: "To", clearFilters: "Clear",
    noRecords: "No records found", tryFilters: "Try clearing the filters",
    previous: "Previous", next: "Next",
    addAttendance: "Add Attendance Record", selectEmployee: "Select Employee",
    notCheckedIn: "Not checked in yet today", currentlyInOffice: "Checked in",
    deleteConfirm: "Delete this record?",
    recordAdded: "Record added successfully!", recordDeleted: "Record deleted",
    checkInSuccess: "Check-in recorded successfully!",
    checkOutSuccess: "Check-out recorded successfully!",
    // Employees
    employeeName: "Employee Name", lastName: "Last Name", firstName: "First Name",
    phone: "Phone", password: "Password", role: "Role", department: "Department",
    searchPlaceholder: "Search by name or phone...",
    filters: "Filters", todayStatus: "Today's Status",
    photo: "Photo", photoOptional: "Photo (optional)",
    errorOccurred: "An error occurred", employeeAdded: "Employee added successfully",
    addNewEmployee: "Add New Employee", fillAllFields: "Fill all required fields",
    selectDepartment: "Select Department", noDepartment: "No Department",
    addDepartment: "Add Department", departmentName: "Department Name",
    createDepartment: "Create", departmentCreated: "Department created!",
    allDepartments: "All Departments", filterByDept: "By department...",
    // Employee Profile
    employeeProfile: "Employee Profile", profileSubtitle: "View and manage employee details",
    deactivate: "Deactivate", editProfile: "Edit Profile",
    faceIdEnrollment: "Face ID Enrollment", notSet: "NOT SET",
    faceEnrolled: "Face biometric enrolled",
    noFaceData: "No face data enrolled. Click below to set up Face ID for this employee.",
    reEnroll: "Re-enroll", enrollFace: "Enroll Face",
    contactDetails: "Contact Details", joined: "Joined",
    lastCheckIn: "Last Check-in", monthlyStats: "Monthly Stats",
    daysOff: "Days Off", attendanceHeatmap: "Attendance heatmap",
    recentRecords: "Recent Records", attendanceRate: "attendance rate",
    confirmDeactivate: "Are you sure you want to deactivate the employee?",
    confirmDeleteFace: "Are you sure you want to delete Face ID data?",
    profileUpdated: "Profile updated", faceSaved: "Face ID saved successfully!",
    // Leaves
    leavesSubtitle: "Manage your leave balances and requests", newRequest: "New Request",
    remaining: "Remaining", left: "left", used: "Used", total: "Total",
    leaveType: "Leave Type", startDate: "Start Date", endDate: "End Date",
    days: "Days", reason: "Reason", newLeaveRequest: "New Leave Request",
    selectType: "Select a type", whyNeedLeave: "Why do you need this leave?",
    submitRequest: "Submit Request", requestSubmitted: "Request submitted successfully!",
    errorSubmitting: "Error submitting request",
    // Payroll
    payrollManagement: "Payroll Management", payrollSubtitle: "Manage employee compensation and calculations",
    payrollRecords: "Payroll Records", salaryConfig: "Salary Configurations",
    workDays: "Work Days", workHours: "Work Hours", overtimeHours: "Overtime Hours",
    baseSalary: "Base Salary", overtimePay: "Overtime Pay", netSalary: "Net Salary",
    configureSalary: "Configure Salary", salaryType: "Salary Type",
    hourly: "Hourly", daily: "Daily", monthly: "Monthly",
    amount: "Amount", overtimeRate: "Overtime Rate", calculateSalary: "Calculate Salary",
    calculationMonth: "Calculation Month", calculating: "Calculating...",
    enterAmount: "Enter a valid amount", configSaved: "Configuration saved",
    errorCalculating: "Error in calculation", deleteConfigConfirm: "Confirm deleting configuration?",
    calculateSubtitle: "Calculates salaries for all employees for the selected month based on attendance data.",
    workDaysDesc: "Based on attendance records", overtimeDesc: "With coefficient from salary config",
    // Team
    teamManagement: "Team Management", teamSubtitle: "Add employees, assign roles and manage your team",
    addEmployee: "Add Employee", contact: "Contact", dateJoined: "Date Joined",
    notAssigned: "Not Assigned", assignRole: "Assign Role", changeRole: "Change Role",
    enterUserDetails: "Enter employee details", editRole: "Edit Role",
    selectNewRole: "Select a new role", roleSaved: "Role saved successfully!",
    teamConfirmDeactivate: "are you sure you want to deactivate this user? This action cannot be undone.",
    teamSearchPlaceholder: "Search by name, email or phone...",
    totalCount: "Total",
    roleOwner: "Company owner with full access",
    roleAdmin: "Wide administrative rights",
    roleManager: "View attendance and reports",
    roleHr: "Personnel management and leaves",
    roleAccountant: "Payroll and financial reports",
    roleEmployee: "View only own data",
    roleGuard: "Attendance monitoring",
    // Reports
    reportsPage: "Reports",
    reportsSubtitle: "Generate and export attendance reports",
    reportConfig: "Report Configuration",
    reportType: "Report Type",
    dateFrom: "From",
    dateTo: "To",
    generate: "Generate",
    generating: "Generating...",
    dataAnalytics: "Data Analytics",
    noAnalytics: "Graphs are only available in the dashboard views.",
    totalEmployeesReport: "Total Employees",
    avgAttendanceReport: "Avg Attendance",
    totalHoursReport: "Total Hours",
    lateArrivalsReport: "Late Arrivals",
    absencesReport: "Absences",
    reportPreview: "Report Preview",
    presentDays: "Present Days",
    lateDays: "Late Days",
    absentDays: "Absent Days",
    overtime: "Overtime",
    rate: "Rate %",
    reportGenerated: "Report generated successfully",
    reportExported: "Report exported successfully",
    exportFailed: "Export failed",
    attendanceSummary: "Attendance Summary",
    lateArrivalsReportFile: "Late Arrivals Report",
    absenceReport: "Absence Report",
    hoursWorkedReport: "Hours Worked Report",
    departmentSummary: "Department Summary",
    // Devices
    devicesManagement: "Devices Management",
    devicesSubtitle: "Connect and manage cameras and Face ID devices",
    addCamera: "Add Camera",
    addFaceId: "Add Face ID",
    cameras: "Cameras",
    faceIdDevices: "Face ID Devices",
    noDevices: "No devices added yet",
    addFirstDevice: "Click the button above to add a new device",
    testConnection: "Test Connection",
    testingConnection: "Testing...",
    lastCheck: "Last Check",
    deviceName: "Device Name",
    location: "Location",
    ipAddress: "IP Address",
    port: "Port",
    macAddress: "MAC Address",
    rtspUrl: "RTSP URL",
    username: "Username",
    checkType: "Check Type",
    both: "Entry & Exit",
    entryOnly: "Entry Only",
    exitOnly: "Exit Only",
    faceThreshold: "Face Recognition Threshold",
    soft: "Soft",
    strict: "Strict",
    networkSettings: "Network Settings",
    deviceLogin: "Device Login Details",
    deviceSettings: "Device Settings",
    apiKey: "API Key",
    copy: "Copy",
    confirmDeleteDevice: "Are you sure you want to delete the device?",
    deviceAdded: "Device added successfully",
    deviceDeleted: "Device deleted",
    connectionSuccess: "Connection successful!",
    connectionFailed: "Connection failed",
    serverError: "Server error",
    entryHistory: "Entry History",
    successful: "Successful",
    rejected: "Rejected",
    successRate: "Rate",
    noHistory: "No history",
    unknown: "Unknown",
    enrolledFaces: "Enrolled Faces",
    employeesEnrolled: "employees enrolled",
    noOneEnrolled: "No one enrolled",
    enrolled: "Enrolled",
    deleteFace: "Delete Face",
    viewHistory: "View History",
    deviceNameRequired: "Device name is required.",
    ipRequired: "IP address is required.",
    deviceUpdated: "Device updated",
    faceDataDeleted: "Face data deleted",
    apiKeyCopied: "API key copied",
    editDevice: "Edit Device",
    mainInfo: "Main Info",
    newPasswordOptional: "New password (optional)",
    unchanged: "Unchanged",
    noDevice: "No devices",
    unknownStatus: "Unknown status",
    // Settings
    settingsSubtitle: "Manage company and system settings",
    profileData: "Personal Data",
    profileDataSubtitle: "Edit your profile information",
    appearanceSubtitle: "Language and theme preferences",
    interfaceLanguage: "Interface Language",
    companyData: "Company Data",
    companySubtitle: "Edit your company core information",
    workSchedule: "Work Schedule",
    workScheduleSubtitle: "Work hours, breaks and overtime settings",
    notificationsSubtitle: "Choose which events you want to be notified about",
    notifLate: "Notify when an employee is late",
    notifAbsent: "Notify when an employee is absent",
    notifOvertime: "Notify about overtime hours",
    notifLeave: "Notify about leave requests",
    securitySubtitle: "Change password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    passwordHint: "Minimum 8 characters",
    passwordRequired: "Fill all fields.",
    passwordLengthError: "New password must be at least 8 characters long.",
    passwordMatchError: "Passwords do not match.",
    passwordChangeError: "Error changing password.",
    saveError: "Error saving.",
    timezone: "Timezone",
    workStart: "Work Start Time",
    workEnd: "Work End Time",
    lunchTime: "Lunch Break (min)",
    lateGrace: "Late Grace (min)",
    lateGraceHint: "Late arrival up to this time is not counted",
    overtimeStart: "Overtime Starts (min)",
    overtimeStartHint: "How many minutes after work does overtime start",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'uz', setLang: () => { }, t: (k) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem('lang') as Lang) || 'uz');

  const setLang = (l: Lang) => { localStorage.setItem('lang', l); setLangState(l); };
  const t = (key: string): string => translations[lang][key] || translations['en'][key] || key;

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
