# Generated by Django 4.2.16 on 2026-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_email_fe4498_idx',
            old_name='accounts_em_email_code_idx',
        ),
    ]
