# Generated by Django 4.2.16 on 2026-03-05 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_branch_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('check_in_method', models.CharField(choices=[('face_id', 'Face ID'), ('pin', 'PIN'), ('qr', 'QR Code'), ('gps', 'GPS'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('late_seconds', models.PositiveIntegerField(default=0)),
                ('net_seconds', models.PositiveIntegerField(default=0)),
                ('overtime_seconds', models.PositiveIntegerField(default=0)),
                ('night_seconds', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('break_seconds', models.PositiveIntegerField(default=0)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancerecord')),
            ],
        ),
    ]
