# Generated by Django 4.2.16 on 2026-03-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_method',
            field=models.CharField(blank=True, choices=[('face_id', 'Face ID'), ('pin', 'PIN'), ('qr', 'QR Code'), ('gps', 'GPS'), ('manual', 'Manual')], max_length=20, null=True),
        ),
    ]
